### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by cryptofuture** [gnd/hydra#3]
First of all I running with `--primary-res 640x480` and turns out hydra memory leaking (tested with threaded version update) for like 40-50mb of memory every second. Overall with my 16Gb of memory (21 including swap) I couldn't  survive more than 30 minutes, without oom-killer. I think it would be easy to reproduce, and just to launch and check process manager would be enough.

**Comment by cryptofuture** [comment]
I tried `https://github.com/erik-smit/sony-camera-api/blob/master/liveView.py` and turns out it has no memory leak, lower cpu usage for the same 640x480, and somehow wider preview angle. Thats weird.

**Comment by gnd** [comment]
Hi, i'm sure the Python liveView API works good ! Hydra on the other hand is a toy project for me to actually learn C properly. Thank you for reporting this issue. I will try to reproduce and fix it.

~~Can you please attach some log / copy paste the data you mention ?~~

Never mind, just verified this, i drained my memory in about 5 minutes..

**Comment by gnd** [comment]
@cryptofuture i believe this has been fixed by https://github.com/gnd/hydra/commit/94a63415830f09c7383e30637e47b2f5529a6687

Please check if it its ok for you too.

**Comment by cryptofuture** [comment]
Just tested running for an hour without any memory issues.
